### PR TITLE
finish implement email functionality

### PR DESCRIPTION
**Pull request by heweiron**
Please test it and give me some feedback about the email system

### CODE REVIEW

**Comment by tianhuizhou** [comment]
good job!

**Comment by kyraikeda** [comment]
i think it works good! only thing is that i have to manually zoom out to see the submit button. this might just be my issue though because my laptop screen is 13". the picture below is what it looks like for me

email

**Comment by heweiron** [comment]
Thank you for finding that error! I fixed it. Can you help me to test it again?

**Comment by kyraikeda** [comment]
great! works perfectly for me now. thanks!!

**Comment by edwin-zheng** [comment]
seems good

**Pull request merged**
